[package]
name = "holokudos-desktop"
version = "1.0.0"
edition = "2021"

[lib]
name = "holokudos_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "holokudos-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-holochain = { version = "0.4" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
holochain_client = "0.6"
holochain_types = "0.4"

[profile.release]
opt-level = "s"     # smaller binary
lto = true
codegen-units = 1
panic = "abort"
strip = true
